services:
  - type: web
    name: BankSimulator
    runtime: node
    repo: https://github.com/Krembovan/BankSimulator
    buildCommand: npm install && npm run build
    startCommand: npm start
    plan: free
